name: BanTicket
main: com.knoxcorner.banticket.BanTicket
version: 1.0
description: Versatile and thorough ban management system
commands:
    bt:
        description: Displays BanTicket related commands
        usage: /bt <page #>
        permission: banticket.bt
    btb:
        description: Permanently bans given player/IP
        usage: /btb <player/IP> <reason>
        permission: banticket.btb
    bttb:
        description: Temporarily bans given player/IP
        usage: /bttb <player/IP> <ban length> <reason>
        permission: banticket.bttp
    btbr:
        description: Submits a request for a permaban on given player
        usage: /btbr <player> <reason>
        permission: banticket.btbr
    bttbr:
        description: Submits a request for a tempban on given player
        usage: /bttbr <player> <length> <reason>
        permission: banticket.bttbr
    btp:
        description: Pardons a player or IP
        usage: /btp <player/IP> <applicaple arguments>
        permission: banticket.btp
    btw:
        description: Warns a player with given message
        usage: /btw <player> <warning message>
        permission: banticket.btw
    btr:
        description: Displays pending ban requests and allows accept/deny
        usage: /btr <ban ID> <accept/deny>
        permission: banticket.btr
    bti:
        description: Attaches extra info to last given ban/warning
        usage: /bti <info>
    btv:
        description: Displays the history of a player with given filter
        usage: /btv <player>
        permission: banticket.btv
    btwr:
        description: Removes the last given warning on a player
        usage: /btwr <player>
        permission: banticket.btwr
#Extra permissions:
#banticket.btb.ip
#banticket.bttb.ip
#banticket.notify.warn
#banticket.notify.ban
