name: BanTicket
main: com.knoxcorner.banticket.BanTicket
version: 1.0
description: Versatile and thorough ban management system
commands:
    bt:
        description: Displays BanTicket related commands
        usage: /bt <subcategory> <applicaple arguments>
    btb:
        description: Displays BanTicket related commands
        usage: /bt <subcategory> <applicaple arguments>
    bttb:
        description: Displays BanTicket related commands
        usage: /bt <subcategory> <applicaple arguments>
    btbr:
        description: Displays BanTicket related commands
        usage: /bt <subcategory> <applicaple arguments>
    bttbr:
        description: Displays BanTicket related commands
        usage: /bt <subcategory> <applicaple arguments>
    btw:
        description: Displays BanTicket related commands
        usage: /bt <subcategory> <applicaple arguments>
    btinfo:
        description: Displays BanTicket related commands
        usage: /bt <subcategory> <applicaple arguments>
